# Generated by Django 5.2.4 on 2025-07-24 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterVariantImage',
            new_name='ProductMasterVariantImage',
        ),
        migrations.RemoveField(
            model_name='level3category',
            name='level2_category',
        ),
        migrations.RemoveField(
            model_name='master',
            name='level2_reference',
        ),
        migrations.RemoveField(
            model_name='master',
            name='level3_reference',
        ),
        migrations.RemoveField(
            model_name='master',
            name='vendor',
        ),
        migrations.RenameModel(
            old_name='MasterVariant',
            new_name='ProductMasterVariant',
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('product_code', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='master-image/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='purchase_module_service.vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='productmastervariant',
            name='master_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='purchase_module_service.productmaster'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='level2-image/')),
                ('delete_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_categories', to='purchase_module_service.category')),
            ],
        ),
        migrations.AddField(
            model_name='productmaster',
            name='sub_category_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchase_module_service.subcategory'),
        ),
        migrations.DeleteModel(
            name='Level2Category',
        ),
        migrations.DeleteModel(
            name='Level3Category',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
