# Generated by Django 5.2.4 on 2025-07-24 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0002_rename_mastervariantimage_productmastervariantimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_reference', models.ForeignKey(default='platforms', on_delete=django.db.models.deletion.CASCADE, to='purchase_module_service.platform')),
                ('product_master_reference', models.ForeignKey(default='platforms', on_delete=django.db.models.deletion.CASCADE, to='purchase_module_service.productmaster')),
            ],
        ),
    ]
