# Generated by Django 5.2.4 on 2025-07-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0002_productvariant_productvariantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
