# Generated by Django 5.2.4 on 2025-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0003_remove_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
