# Generated by Django 5.2.4 on 2025-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0003_platform_productplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='platform',
            field=models.ManyToManyField(default='products', to='purchase_module_service.platform'),
        ),
    ]
