# Generated by Django 5.2.4 on 2025-07-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0004_productvariant_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='MasterVariant',
        ),
        migrations.RenameModel(
            old_name='ProductVariantImage',
            new_name='MasterVariantImage',
        ),
    ]
