# Generated by Django 5.2.4 on 2025-07-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0004_productmaster_platform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPlatform',
            new_name='ProductPlatformMapping',
        ),
        migrations.RenameField(
            model_name='productmaster',
            old_name='platform',
            new_name='platform_reference',
        ),
        migrations.RenameField(
            model_name='productmastervariantimage',
            old_name='variant',
            new_name='variant_reference',
        ),
    ]
