# Generated by Django 5.2.4 on 2025-07-21 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0005_rename_productvariant_mastervariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge', models.CharField(max_length=250)),
                ('delete_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=250)),
                ('color_code', models.CharField(max_length=100)),
                ('delete_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='collar',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='level2category',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='level3category',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='level2_category',
            new_name='level2_reference',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='level3_category',
            new_name='level3_reference',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='collar',
            new_name='collar_reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='master',
            new_name='master_reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='material',
            new_name='material_reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='neck',
            new_name='neck_reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='size',
            new_name='size_reference',
        ),
        migrations.RenameField(
            model_name='mastervariant',
            old_name='sleeve',
            new_name='sleeve_reference',
        ),
        migrations.RenameField(
            model_name='mastervariantimage',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='neck',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='sleeve',
            old_name='id',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='master',
            name='category',
        ),
        migrations.AddField(
            model_name='mastervariant',
            name='offer_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mastervariant',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mastervariant',
            name='tag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mastervariant',
            name='weight',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastervariant',
            name='badge_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.badge'),
        ),
        migrations.AddField(
            model_name='mastervariant',
            name='color_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.color'),
        ),
    ]
