# Generated by Django 5.2.4 on 2025-07-23 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0006_badge_color_rename_id_category_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastervariant',
            name='badge_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.badge'),
        ),
        migrations.AlterField(
            model_name='mastervariant',
            name='collar_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.collar'),
        ),
        migrations.AlterField(
            model_name='mastervariant',
            name='color_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.color'),
        ),
        migrations.AlterField(
            model_name='mastervariant',
            name='material_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.material'),
        ),
        migrations.AlterField(
            model_name='mastervariant',
            name='neck_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.neck'),
        ),
        migrations.AlterField(
            model_name='mastervariant',
            name='size_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.size'),
        ),
        migrations.AlterField(
            model_name='mastervariant',
            name='sleeve_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.sleeve'),
        ),
        migrations.DeleteModel(
            name='MasterVariantImage',
        ),
    ]
