# Generated by Django 5.2.4 on 2025-07-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0006_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmastervariant',
            name='season_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_module_service.season'),
        ),
    ]
