# Generated by Django 5.2.4 on 2025-07-23 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0007_alter_mastervariant_badge_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVariantImage',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='variant-images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='purchase_module_service.mastervariant')),
            ],
        ),
    ]
