# Generated by Django 5.2.4 on 2025-07-23 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0008_mastervariantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
