# Generated by Django 5.2.4 on 2025-07-24 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0008_platform_created_on_platform_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productplatformmapping',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 24, 7, 2, 32, 741529, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productplatformmapping',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
