# Generated by Django 5.2.4 on 2025-07-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0009_productplatformmapping_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
