# Generated by Django 5.2.4 on 2025-07-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0010_remove_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='vendor',
        ),
    ]
