# Generated by Django 5.2.4 on 2025-07-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0011_remove_productmaster_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPlatformMapping',
        ),
    ]
