# Generated by Django 5.2.4 on 2025-07-24 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0012_delete_productplatformmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPlatformMapping',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('platform_reference', models.ForeignKey(default='platforms', on_delete=django.db.models.deletion.CASCADE, to='purchase_module_service.platform')),
                ('product_master_reference', models.ForeignKey(default='platforms', on_delete=django.db.models.deletion.CASCADE, to='purchase_module_service.productmaster')),
            ],
        ),
    ]
