# Generated by Django 5.2.4 on 2025-07-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0013_productplatformmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='sub_category_reference',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
