# Generated by Django 5.2.4 on 2025-07-24 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0014_remove_productmaster_sub_category_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='subcategory-image/')),
                ('delete_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='purchase_module_service.category')),
            ],
        ),
        migrations.AddField(
            model_name='productmaster',
            name='sub_category_reference',
            field=models.ForeignKey(default='6e7e6b18-28ab-4c2e-bc67-1db6e30e340b', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchase_module_service.subcategory'),
            preserve_default=False,
        ),
    ]
