# Generated by Django 5.2.4 on 2025-07-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_module_service', '0015_subcategory_productmaster_sub_category_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmastervariant',
            old_name='master_reference',
            new_name='product_master_reference',
        ),
    ]
